### ISSUE TITLE
View Code Not Working

### ISSUE THREAD

**Issue by hartman19** [arbelatech/aotbrowser#24]
Hi everyone,
I have installed the template on a sandbox environment version 10.0.31 (10.0.1406.139), but even activating the source code view feature does not display the screen as per the documentation.
![image](https://user-images.githubusercontent.com/9819355/234516857-5501cf60-5ade-48aa-8132-6e9a1196e004.png)

**Comment by caleblanchard** [comment]
Can you clarify what you mean by a sandbox environment? Are you referring to a cloud-hosted environment?

**Comment by AvrDen81** [comment]
> Can you clarify what you mean by a sandbox environment? Are you referring to a cloud-hosted environment?

I'm seeing the same problem on the On-prem environment. Please help)

**Comment by caleblanchard** [comment]
> > Can you clarify what you mean by a sandbox environment? Are you referring to a cloud-hosted environment?
> 
> I'm seeing the same problem on the On-prem environment. Please help)

Sorry, I am still not clear. What type of environment are you referring to? The reason I am asking is that the AOT browser can only show code on environments where source code exists. If the environment does not have the source code, but only has the binaries, then it will not be possible to show the code.

For example, a Tier2 or a Production environment will not be able to show the source code because there is no source code on those topologies. Whereas, a cloud-hosted development or demo environment, or the downloadable Onebox VM should be able so show the source code, since the source code is no those topology types.

**Comment by AvrDen81** [comment]
> Sorry, I am still not clear. What type of environment are you referring to? The reason I am asking is that the AOT browser can only show code on environments where source code exists. If the environment does not have the source code, but only has the binaries, then it will not be possible to show the code.
> 
> For example, a Tier2 or a Production environment will not be able to show the source code because there is no source code on those topologies. Whereas, a cloud-hosted development or demo environment, or the downloadable Onebox VM should be able so show the source code, since the source code is no those topology types.

Thank you. Yes, the question was about PROD environment
